# Generated by Django 3.0.4 on 2020-03-21 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('workflow_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='pending', max_length=10)),
                ('created_datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('approved_by', models.CharField(blank=True, max_length=30)),
                ('modified_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
