# Generated by Django 3.0.4 on 2020-03-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='workflow_id',
            new_name='approval_id',
        ),
    ]
